<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SGHSS.Application\SGHSS.Application.csproj" />
    <ProjectReference Include="..\SGHSS.Infrastructure\SGHSS.Infrastructure.csproj" />
  </ItemGroup>

</Project>
